application: gcdc2013-neverpass
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
# static
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /lib
  static_dir: static/lib
# Auth
#- url: /login
#  script: handlers/login.php
#- url: /logout
#  script: handlers/logout.php
# Page + API
#- url: /api/channel
#  script: handlers/api/channel.php
#- url: /([\w]{32})?
#  script: handlers/main.php
# 404
- url: .*
  script: handlers/index.php