application: gcdc2013-neverpass
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: javascript
- url: /map
  script: handlers/map.php
- url: /login
  script: handlers/login.php
- url: /logout
  script: handlers/logout.php
- url: /api/channel
  script: handlers/api/channel.php
- url: .*
  script: handlers/main.php
