application: gcdc2013-neverpass
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /login
  script: handlers/login.php
- url: /logout
  script: handlers/logout.php
- url: .*
  script: handlers/main.php
