application: gcdc2013-neverpass
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /lib
  static_dir: static/lib
- url: /login
  script: handlers/login.php
- url: /logout
  script: handlers/logout.php
- url: /api/channel
  script: handlers/api/channel.php
- url: /\w{32}
  script: handlers/main.php
- url: /
  script: handlers/main.php
- url: /play
  script: handlers/play.php
- url: .*
  script: handlers/404.php