Google_PlusService:
  ClientId: YOUR_CLIENTID
  ClientSecret: YOUR_CLIENTSECRET
  RedirectUri: /login
  DeveloperKey: YOUR_APIKEY
Database:
  host: YOUR_IT_OR_HOSTNAME
  username: YOUR_USERNAME
  password: YOUR_PASSWORD
  dbname: YOUR_DATABASE_NAME
  socket: YOUR_SOCKET